cache_size_limit: 52428800
chunk_size: 1000
cleanup_interval: 300
logging:
  file: logs/doc_processor.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
max_paragraphs_to_search: 30
max_processes: 5
max_tables_to_search: 5
memory_limit: 1073741824
preview: false
skip_count_check: false
verbose: false
