version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  error:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s\nStack trace:\n%(stack_info)s"

handlers:
  console:
    class: rich.logging.RichHandler
    level: INFO
    formatter: standard
    show_time: true
    show_level: true
    show_path: true
    rich_tracebacks: true
    tracebacks_show_locals: true

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/doc_processor.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: logs/doc_processor_error.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf8

loggers:
  '':  # root logger
    handlers: [console, file, error_file]
    level: DEBUG
    propagate: true

  doc_processor:
    handlers: [console, file, error_file]
    level: DEBUG
    propagate: false

  doc_processor.parser:
    handlers: [console, file, error_file]
    level: DEBUG
    propagate: false

  doc_processor.processor:
    handlers: [console, file, error_file]
    level: DEBUG
    propagate: false
