disable_existing_loggers: false
formatters:
  simple:
    format: '%(levelname)s - %(message)s'
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file:
    backupCount: 10
    class: logging.handlers.RotatingFileHandler
    encoding: utf8
    filename: logs/doc_processor.log
    formatter: standard
    level: DEBUG
    maxBytes: 10485760
loggers:
  ? ''
  : handlers:
    - console
    - file
    level: INFO
    propagate: true
  doc_processor:
    handlers:
    - console
    - file
    level: DEBUG
    propagate: false
version: 1
